### PR TITLE
Misc test fixes

### PR DESCRIPTION
**Pull request by jzohrab**
A few misc fixes to make the testing more enjoyable (for me, anyway, and hopefully for others as well):

**Fix test headers.**

Currently, the tests are shown right at the top of the screen, eg:

current_tests_no_header

The first commit restores the header:

image

**Speed things up**

During heavy usage, the right frame slide-ins-and-outs become distracting and annoying.

**Faster test actions**

The last two commits let me see and set the answers and statuses more quickly.  I can just "enter-enter-enter-enter" to rapidly go through all tests, without having to mouse everywhere, and I don't have to see any pop-ups to say whether I passed or failed ... I know if I passed or failed. :-)

### CODE REVIEW

**Comment by HugoFara** [comment]
Hi Jeff!

I'm testing branch, but unfortunately I cannot get a normal behavior. When I test a word on Firefox, the page starts loop-reloading multiple time, which is quite annoying, unless I press enter again. Could you give me more details about the intended behavior?

Until now:
* **Fix test header**: I used your code from the first commit to fix this bug (see [3664fc2](https://github.com/HugoFara/lwt/commit/3664fc2a89dd404b6c44b0a685b9b434d5b9bcfa))
* **Speed things up**: I think I could see the intended behavior here, but fast-moving frames do no seem a very good solution, I think fixed frames may be better as suggested in #60
* **Faster test actions**: doesn't work on Firefox, but no problem so far with Chrome. Here, have you tried to use up and down arrows? I believe they do what you want, now I think I should write tutorials :sweat_smile:

**Comment by jzohrab** [comment]
Ah too bad it wasn't working for you, for me it's good. :-)  The key events are used in the same place as the other test keys, so I really can't see how it's going into an infinite loop.  :-/

Intended behaviour:

* test is displayed.  When I hit Return, the answer is shown in-line (e.g., "Ella tiene un **gato**" => "Ella tiene un **[cat]**")
* if I hit Return when the in-line answer is shown, the question is immediately marked as "Passed", and the next question is shown.

re "faster test actions", yes I use the arrow keys, and with this branch I can do it without having the "side window" open (which the javascript used to require):

* test is displayed.  When I hit Return, the answer is shown in-line (e.g., "Ella tiene un **gato**" => "Ella tiene un **[cat]**")
* if I hit the up or down array when the in-line answer is shown, the question is immediately marked as "Passed" or "Failed" respectively, and the next question is shown.

Cheers! jz

**Comment by HugoFara** [comment]
Okay, I went back on main branches, and the infinite loop is already present, whenever I use keyboard actions :|
So, I come back to this PR as soon as I get this issue fixed!

**Comment by HugoFara** [comment]
Hi! I solved the bug causing **Faster test actions** to loop-reload on Firefox. I was caused by ``setTimeout('window.parent.location.reload();', waittime);`` on ``set_test_status.php``. Since the context is lost using window.parent.location.reload() after a Timeout, Chrome was solving the location to the *parent* window, while Firefox was using the *current* window, so the current iframe. Doing so, the iframe was calling itself in loops.

The solution was to use ``setTimeout(window.location.reload.bind(window.parent.location), waittime)``. It's a bit long, but it avoids confusion.

I think the issue was related to the fact that you changed the timeout value. As you deleted the branch, do you want me to try your code?

**Pull request closed without merging**
