### PR TITLE
[Feature] Download audio from Youtube and others from Audio URI

### PR DESCRIPTION
**Pull request by ProgramComputer**
Built upon #156. This is a step above #156 but optional if Youtube and web extractors is too much. If either youtube-dl or ytd-dl is installed in path and set-tts(save audio to disk) in settings is set. Youtube, vimeo, and Dailymotion URLs will download to the media path.

https://github.com/ProgramComputer/lwt/blob/ab016735b89d95bcc9b36bfe6db8411e1ca2c530/INSTALL.sh#L64 

is important permission-wise for this feature.

If either is installed, putting a link in text import will show a button to get subtitles.

### CODE REVIEW

**Comment by HugoFara** [comment]
Hi, I think this feature is a bit too much as it may need a lot of maintaining cost. Downloading a video don't take much time either so I don't think it's worth implementing for now, but it is a nice idea. Maybe you can show it on [Discussions](https://github.com/HugoFara/lwt/discussions) for those interested?

**Comment by ProgramComputer** [comment]
> Hi, I think this feature is a bit too much as it may need a lot of maintaining cost. Downloading a video don't take much time either so I don't think it's worth implementing for now, but it is a nice idea. Maybe you can show it on [Discussions](https://github.com/HugoFara/lwt/discussions) for those interested?

@HugoFara Can you leave it as a draft? This would succeed text_from_yt.php.

**Comment by HugoFara** [comment]
Why do you need it as a draft? Moreover, due to the numerous changes since the intial PR, it will be easier for me to copy your code than merging this PR...

**Comment by HugoFara** [comment]
I'm not planning on implementing it for now, I think of it as a nice *extension* to LWT capabilities, but I'm not reading to keep up on the maintaining cost.

**Pull request closed without merging**
